# Generated by Django 4.2.5 on 2023-10-04 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_list', '0002_alter_productlist_price'),
        ('user', '0002_alter_user_email_alter_user_name_alter_user_password'),
        ('product', '0002_rename_filter_product_content_remove_product_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=30)),
                ('product_path', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('total', models.IntegerField()),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('product_list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_list.productlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
