# Generated by Django 4.2.6 on 2023-10-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='added_on',
            new_name='created_at',
        ),
    ]
