# Generated by Django 4.2.6 on 2023-10-24 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingaddress',
            old_name='district',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='billingaddress',
            old_name='user_name',
            new_name='last_name',
        ),
    ]
