# Generated by Django 4.2.5 on 2023-10-01 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0002_rename_filter_product_content_remove_product_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image_path', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('stack_quantity', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('content', models.CharField(null=True)),
                ('manufacturer_from', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
