# Generated by Django 4.2.5 on 2023-10-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlist',
            name='price',
            field=models.IntegerField(max_length=50),
        ),
    ]
