# Generated by Django 4.2.5 on 2023-10-02 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_alter_user_email_alter_user_name_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oder_ids', models.CharField(null=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('pincode', models.IntegerField(null=True)),
                ('message', models.CharField(max_length=1000)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
