# Generated by Django 4.2.5 on 2023-10-02 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='oder_ids',
        ),
    ]
