# Generated by Django 4.2.6 on 2023-10-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('billing_address', '0002_rename_district_billingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPivotIds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_address.billingaddress')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.oderdetails')),
            ],
            options={
                'db_table': 'order_pivot_ids',
            },
        ),
    ]
