# Generated by Django 4.2.6 on 2023-10-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('order_tracking', '0001_initial'),
        ('payment', '0002_payment_order_id'),
        ('order_pivot_ids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpivotids',
            name='order_tracking_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order_tracking.ordertracking'),
        ),
        migrations.AddField(
            model_name='orderpivotids',
            name='payment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='payment.payment'),
        ),
        migrations.AddField(
            model_name='orderpivotids',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
