# Generated by Django 4.2.6 on 2023-10-29 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_placed', models.BooleanField(null=True)),
                ('order_processed', models.BooleanField(null=True)),
                ('order_ready_to_ship', models.BooleanField(null=True)),
                ('order_shipped', models.BooleanField(null=True)),
                ('shipping_details', models.CharField(null=True)),
                ('order_delivered', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'order_tracking',
            },
        ),
    ]
