# Generated by Django 4.2.6 on 2023-10-28 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_payment_success', models.BooleanField(null=True)),
                ('is_upi', models.BooleanField(null=True)),
                ('upi_amount_payed', models.IntegerField(null=True)),
                ('is_cash_on_delivery', models.BooleanField(null=True)),
                ('cash_amount_payed', models.IntegerField(null=True)),
                ('is_verified_by_admin', models.BooleanField(null=True)),
                ('payment_verified_admin_name', models.CharField()),
                ('payment_verified_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
