# Generated by Django 4.2.6 on 2023-10-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscribe',
            table='subscribe',
        ),
    ]
