# Generated by Django 4.2.6 on 2023-10-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_alter_subscribe_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='added_on',
            new_name='created_at',
        ),
    ]
