# Generated by Django 4.2.6 on 2023-10-12 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_rename_added_on_product_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_code', models.CharField(max_length=5, unique=True)),
                ('item_name', models.CharField(max_length=10)),
                ('item_grade', models.CharField(max_length=10, unique=True)),
                ('item_img_path', models.CharField(max_length=30)),
                ('item_desc', models.CharField(max_length=5000)),
                ('item_price', models.IntegerField()),
                ('stack_qty', models.IntegerField()),
                ('available_qty', models.IntegerField()),
                ('manufacturer_from', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'product_items',
            },
        ),
    ]
