# Generated by Django 4.2.6 on 2023-10-12 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productitem',
            old_name='product',
            new_name='product_id',
        ),
    ]
