# Generated by Django 4.2.5 on 2023-09-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=6)),
                ('stack_quantity', models.CharField(max_length=5)),
                ('grade', models.CharField(max_length=3)),
                ('manufacturer_from', models.CharField(max_length=30)),
                ('filter', models.CharField(null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
