# Generated by Django 4.2.5 on 2023-10-01 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='filter',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='product',
            name='grade',
        ),
    ]
