# Generated by Django 4.2.6 on 2023-10-12 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=30)),
                ('is_admin', models.BooleanField(default=False)),
                ('mobile_otp', models.IntegerField(blank=True, null=True)),
                ('mobile_otp_generate_timestamp', models.DateTimeField(blank=True, null=True)),
                ('email_otp', models.IntegerField(blank=True, null=True)),
                ('email_otp_generate_timestamp', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
