# Generated by Django 4.2.5 on 2023-10-01 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
        ('product', '0002_rename_filter_product_content_remove_product_grade'),
        ('cart', '0002_rename_user_id_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product_list.productlist'),
        ),
    ]
