# Generated by Django 4.2.6 on 2023-10-15 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('billing_address', '0001_initial'),
        ('products', '0002_rename_added_on_product_created_at'),
        ('product_items', '0002_rename_product_productitem_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oderdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing_address.billingaddress')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('product_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_items.productitem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
