# Generated by Django 4.2.6 on 2023-10-15 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing_address', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oderdetails',
            name='billing_address_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing_address.billingaddress'),
        ),
    ]
