# Generated by Django 4.2.6 on 2023-10-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_oderdetails_billing_address_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='oderdetails',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='oderdetails',
            name='is_order_placed',
            field=models.BooleanField(default=True),
        ),
    ]
